<div style="border: 2px solid black; padding: 10px; background-color: #f7f7f7; text-align: center;">
    <h1 style="color: Navy; text-decoration: underline;">TP2: Machine Learning II</h1>
</div>


In [1]:
import gymnasium as gym
import numpy as np

####   Exercie1 : Découverte et exploration d’un environnement Gym


In [4]:
# Création de l’environnement FrozenLake
env =gym.make("FrozenLake-v1",is_slippery=True)
# Affichage des espaces
print("Espace des états :", env.observation_space.n)
print("Espace des actions :", env.action_space.n)

# Exécution d’actions aléatoires
for episode in range(5):
    state, info = env.reset()
    done = False
    print(f"\nÉpisode {episode+1}")
    while not done:
        action = env.action_space.sample()
        new_state, reward, done, truncated, info = env.step(action)
        print(f"État : {state}, Action : {action}, Nouveau état : {new_state}, Récompense : {reward}")
        state = new_state


Espace des états : 16
Espace des actions : 4

Épisode 1
État : 0, Action : 0, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 0, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 3, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 2, Nouveau état : 1, Récompense : 0.0
État : 1, Action : 0, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 1, Nouveau état : 1, Récompense : 0.0
État : 1, Action : 0, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 1, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 2, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 1, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 1, Nouveau état : 4, Récompense : 0.0
État : 4, Action : 1, Nouveau état : 4, Récompense : 0.0
État : 4, Action : 3, Nouveau état : 5, Récompense : 0.0

Épisode 2
État : 0, Action : 0, Nouveau état : 0, Récompense : 0.0
État : 0, Action : 2, Nouveau état : 1, Récompense : 0.0
État : 1, Action : 2, Nouveau état : 5, Récompense : 0.0

Épisode 3
État : 0, 

#### Exercice 2 : Implémentation de la Q-Table: 


In [5]:
# Initialisation de la Q-Table (n_states x n_actions)
q_table = np.zeros((env.observation_space.n, env.action_space.n))

# Affichage de la Q-Table initiale
print("Q-Table initialisée :")
print(q_table)


Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Exercice 3 : Implémentation de Q-learning avec mise à jour

In [6]:
# Hyperparamètres
alpha = 0.1           # taux d’apprentissage
gamma = 0.99          # facteur de discount
epsilon = 1.0         # exploration initiale
epsilon_decay = 0.995
min_epsilon = 0.01
num_episodes = 5000

# Entraînement de l’agent
for episode in range(num_episodes):
    state, info = env.reset()
    done = False

    while not done:
        # Choix de l’action : exploration ou exploitation
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state, :])

        # Exécution de l’action
        new_state, reward, done, truncated, info = env.step(action)

        # Mise à jour de la Q-Table
        old_value = q_table[state, action]
        next_max = np.max(q_table[new_state, :])
        new_value = old_value + alpha * (reward + gamma * next_max - old_value)
        q_table[state, action] = new_value

        state = new_state

    # Mise à jour du taux d’exploration
    epsilon = max(min_epsilon, epsilon * epsilon_decay)

# Affichage final de la Q-Table
print("Q-Table après apprentissage :")
print(q_table)


Q-Table après apprentissage :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Exercice 4 : Évaluation des Performances de l’Agent


In [10]:
num_test_episodes = 100
successes = 0

for _ in range(num_test_episodes):
    state, info = env.reset()
    done = False
    while not done:
        action = np.argmax(q_table[state, :])  # Action optimale
        state, reward, done, truncated, info = env.step(action)
        if done and reward == 1:
            successes += 1

# Affichage du taux de réussite
print(f"Taux de réussite sur {num_test_episodes} épisodes : {successes}%")


Taux de réussite sur 100 épisodes : 0%
